### ISSUE TITLE
How to upload my custom template once the docker-compose up is done

### ISSUE THREAD

**Issue by BalmanRawat** [jeshan/viz-cfn#1]
Hello thank you for your work, I have downloaded this repo and `docker-compose up` it is up but shows only samples templates by default. How do I upload my custom templates. 

### Screenshot
<img width="1124" alt="Screen Shot 2019-03-28 at 3 47 32 PM" src="https://user-images.githubusercontent.com/8892649/55148729-def07b80-5170-11e9-8648-aab38a157659.png">

**Comment by jeshan** [comment]
This list is hardcoded in the html file. The app doesn't keep track of
uploaded files; it just uses it to generate the visualisation. You should
list your files in the html for now.
